GoogleCloudPlatform/bank-of-anthos

.github/workflows/smoke-tests.yml
src/frontend/templates/signup.html
src/loadgenerator/locustfile.py
src/loadgenerator/requirements.in
src/loadgenerator/requirements.txt

Resolves GitHub security alert about one of the dependencies

Update load generator

---

.github/workflows/README.md

Improve worker VM setup instructions

---

src/accounts-db/initdb/0-accounts-schema.sql

Ensure contact labels are NOT NULL in accounts-db

---

src/frontend/flask_server.py
src/userservice/userservice.py

Frontend shows error messages in the UI for failed requests

---

.github/workflows/install-dependencies.sh

Otherwise a failed command won't cause script to terminate.

Add strict mode to script

---

README.md

Fix service summary and deployment instructions in root README

---

kubernetes-manifests/accounts-db.yaml
kubernetes-manifests/balance-reader.yaml
kubernetes-manifests/contacts.yaml
kubernetes-manifests/frontend.yaml
kubernetes-manifests/ledger-db.yaml
kubernetes-manifests/ledger-writer.yaml
kubernetes-manifests/loadgenerator.yaml
kubernetes-manifests/transaction-history.yaml
kubernetes-manifests/userservice.yaml

fixes https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/123
- Add resource requests/limits to missing services.
- ask for the same resources for services of the same language
- tried to base numbers off of the values seen with `kubectl top pod`, with some added head room

Resource requests

---

Makefile
README.md

This should be able to be set to demo in appropriate region.

Don't hard code zone

---

docs/development.md

fixes https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/221

Added links to development guide

---

kubernetes-manifests/transaction-history.yaml
src/transactionhistory/README.md
src/transactionhistory/pom.xml
src/transactionhistory/src/main/java/anthos/samples/financedemo/transactionhistory/LedgerReader.java
src/transactionhistory/src/main/java/anthos/samples/financedemo/transactionhistory/TransactionHistoryApplication.java
src/transactionhistory/src/main/java/anthos/samples/financedemo/transactionhistory/TransactionHistoryController.java
src/transactionhistory/src/main/resources/application.properties
src/transactionhistory/src/main/resources/log4j2.xml

Implemented logging for the transactionhistory service, this fixes #217 . Also removes the banner :)
Example log:

Added logging to transactionhistory service

---

kubernetes-manifests/loadgenerator.yaml
src/loadgenerator/Dockerfile
src/loadgenerator/README.md
src/loadgenerator/loadgen.sh
src/loadgenerator/locustfile.py

Locust already has a logging setup and after discussing with Megan we will be following it, this just allows us to set the locust logging log level and fixes #218

adds loglevel to loadgenerator

---

kubernetes-manifests/frontend.yaml
src/contacts/README.md
src/frontend/Dockerfile
src/frontend/flask_server.py
src/frontend/logging.conf

adds standardized logging for the frontend service

---

kubernetes-manifests/balance-reader.yaml
kubernetes-manifests/config.yaml
kubernetes-manifests/contacts.yaml
kubernetes-manifests/transaction-history.yaml
src/balancereader/README.md
src/transactionhistory/README.md

removes global log level env var

---

src/frontend/README.md
src/frontend/flask_server.py
src/frontend/templates/index.html
src/frontend/templates/login.html
src/frontend/templates/signup.html

Follow up from #234.
This PR implements a `BANK_NAME` environment variable that can be set for the `src/frontend` service to override the name in the NavBar and HTML title. This is useful for demo'ing ASM / multiple deployments where you want to show visible differences in the UI.

Implement BANK_NAME variable

---

src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/BalanceReaderController.java
src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/JWTVerifierGenerator.java

This is so that I can write tests for the balancereader service more easily.
This closes #283

Refactored JWT verifier into a separate class

---

src/balancereader/src/main/resources/application.properties
src/ledgerwriter/src/main/resources/application.properties
src/transactionhistory/src/main/resources/application.properties

Fixes #297. Was due to a bean creation issue marked here: https://github.com/jacoco/jacoco/issues/531.

Fixes jacoco logging dependency issue

---

src/transactionhistory/pom.xml
src/transactionhistory/src/main/java/anthos/samples/bankofanthos/transactionhistory/JWTVerifierGenerator.java
src/transactionhistory/src/main/java/anthos/samples/bankofanthos/transactionhistory/TransactionCache.java
src/transactionhistory/src/main/java/anthos/samples/bankofanthos/transactionhistory/TransactionHistoryController.java
src/transactionhistory/src/test/java/anthos/samples/bankofanthos/transactionhistory/TransactionHistoryControllerTest.java
src/transactionhistory/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This fixes #163. Also has refactoring of cache into `TransactionCache` and jwtVerifier into `JWTVerifierGenerator`.

Add tests for transactionhistory controller

---

dev-kubernetes-manifests/frontend.yaml

Increase frontend readiness probe timeout

---

.github/workflows/ci.yaml
skaffold.yaml

Fixes non-existent namespace error in kubectl get namespace. Changes the namespace creation in CI workflow and increases timeout for skaffold healthcheck.

fix non-existent namespace error

---

.github/pull_request_template.md
CONTRIBUTING.md
docs/development.md

Update development guide, add PR template

---

.github/workflows/ci.yaml

Adds test coverage reporting for TransactionHistory

---

dev-kubernetes-manifests/balance-reader.yaml
dev-kubernetes-manifests/contacts.yaml
dev-kubernetes-manifests/ledger-writer.yaml
dev-kubernetes-manifests/transaction-history.yaml
dev-kubernetes-manifests/userservice.yaml

Increase readiness probe delay for Java services

---

.github/workflows/README.md

Extends Github Actions documentation 

---

.github/workflows/ci.yaml

Fixes #320 
- adds comment with external ip
- adds comment each time CI is run

CI comments PR with staged IP

---

.github/workflows/ci-master.yaml
.github/workflows/ci-pr.yaml
.github/workflows/ci.yaml

Pushes to master don't have a `COMMENTS_URL`.

Fix staging IP error in CI (separate workflows) 

---

README.md
docs/troubleshooting.md

Add initial troubleshooting guide

---

.github/workflows/ci-pr.yaml

Fixes #364 
- Adds clear flag to venv, this deletes the directory if it already exists and starts a fresh one

Fixes failing python tests, clears venv dir

---

.github/workflows/ci-master.yaml

Updates ci-master.yaml with --clear flag.

Add --clear flag to python venv setup [CI master]

---

Makefile

Fixes #365 and issues found during fishfood.
- removed beta from make cluster
- removed e2e-env, e2e url moved to test-e2e
- added unit tests

v0.3 fishfood: Makefile changes

---

.github/workflows/ci-pr.yaml

https://github.community/t/running-code-from-forks-with-pull-request-target/126688/5

Fix actions/checkout invocation for pull_request_target

---

src/loadgenerator/locustfile.py

Typo fix: redirets => redirects

---

src/frontend/static/styles/cymbal.css
src/frontend/templates/index.html

Addresses #294 
Same changes as https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/302

Swap credit/debit labels in UI

---

.github/prod-cluster/frontend-ingress.yaml
.github/prod-cluster/frontend-nodeport.yaml

(Networking resources for bank-of-anthos.xyz ingress)

Adds NodePort service and Ingress for prod cluster

---

extras/cloudsql-multicluster/README.md

- Correct a typo in multi-cluster instructions

Correct a typo in multi-cluster instructions

---

release/README.md

- Update few details related to releasing the repo and deploying 
- NA

Update release instructions

---

extras/cloudsql-multicluster/README.md
extras/tls-ip-selfsigned/README.md

- Apply @robkelly's suggested nits from [custom-samples-example #44](https://github.com/GoogleCloudPlatform/cloud-code-custom-samples-example/pull/44)
It was difficult for me to find the right documentation on how to set up an Anthos license. If the term "license" is interchangeable with "subscription", it might make sense to replace "An active Anthos license" with "An active Anthos subscription", or to ~include a link to [Pricing & Trials](https://cloud.google.com/kubernetes-engine/docs/concepts/multi-cluster-ingress#pricing_and_trials) for more info.~ **UPDATE:** added the link.

Minor readability changes

---

README.md

Closes #518. Updates instructions to include GKE Autopilot mode.

Update for autopilot

---

extras/cloudsql-multicluster/README.md
extras/cloudsql/README.md
extras/cloudsql/create_cloudsql_instance.sh
extras/cloudsql/kubernetes-manifests/balance-reader.yaml
extras/cloudsql/kubernetes-manifests/config.yaml
extras/cloudsql/kubernetes-manifests/contacts.yaml
extras/cloudsql/kubernetes-manifests/frontend.yaml
extras/cloudsql/kubernetes-manifests/ledger-writer.yaml
extras/cloudsql/kubernetes-manifests/loadgenerator.yaml
extras/cloudsql/kubernetes-manifests/transaction-history.yaml
extras/cloudsql/kubernetes-manifests/userservice.yaml

Fixes #
https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/507
- Brought /extras/cloudsql/kubernetes-manifests up to date with /kubernetes-manifests
- Updated gce-proxy from 1.19.0-alpine to 1.24.0-alpine

CloudSQL updates

---

extras/cloudshell/tutorial.md

**Change summary**
Update sections of the Cloud Shell interactive tutorial, in accordance with changes made to the Cloud Shell Editor UI.
**View staged tutorial**
Review the staged changes to the tutorial in Cloud Shell: [Open in Cloud Shell](https://ssh.cloud.google.com/cloudshell/editor?show=ide&cloudshell_git_repo=https://github.com/kelsk/bank-of-anthos&cloudshell_git_branch=cloudshell-tutorial&cloudshell_workspace=.&cloudshell_tutorial=extras/cloudshell/tutorial.md)

Update Cloud Shell tutorial

---

.github/snippet-bot.yml

n/a
To track region tags when they get added to our files
Added the snippet-bot.yml file under .github (empty)
We don't have any region tags in this project yet, but just expect a verbose bot on prs.
n/a
n/a

Added snippet bot yml file

---

kubernetes-manifests/accounts-db.yaml
kubernetes-manifests/balance-reader.yaml
kubernetes-manifests/contacts.yaml
kubernetes-manifests/frontend.yaml
kubernetes-manifests/ledger-db.yaml
kubernetes-manifests/ledger-writer.yaml
kubernetes-manifests/loadgenerator.yaml
kubernetes-manifests/transaction-history.yaml
kubernetes-manifests/userservice.yaml

This PR releases `v0.5.3`.
**Release guide:** https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/master/release
**Release notes (v0.5.3):** https://github.com/GoogleCloudPlatform/bank-of-anthos/releases/tag/untagged-8fb2053bda19c326d50e

Release v0.5.3

---

src/loadgenerator/Dockerfile
src/loadgenerator/locustfile.py

I was pointed out an issue with Locust that started to appear when it was bumped version, in which it would build, but fail to run properly. This PR fixes this by following the guidelines here: https://docs.locust.io/en/stable/changelog.html#other-breaking-changes
I tested it by deploying on a cluster. You can see locust running multiple tests without any errors:
```
Name                                                                              # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
----------------------------------------------------------------------------------------------------------------------------------------------------------------
GET /                                                                                139     1(0.72%)  | …
```

Remove deprecated artifacts from locust

---

docs/development.md

Directory in the previous step is `/opt/jdk17` so I believe this is what JAVA_HOME should be.

Update JAVA_HOME profile to reflect correct path in `/opt/`

---

release/README.md

This PR slightly tweak the releasing README.

Tweak the releasing README

---

README.md

This PR removes the temporary log4j advisory since it's been over 4 months, and tweaks the README in minor ways.

Tweak README and remove Log4j advisory

---

.gitignore
extras/asm-multicluster/README.md
extras/asm-multicluster/cluster-setup.sh

See https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/752
Updated asm-multicluster to use `asmcli` and other best practices
Tested locally on new projects

Updated asm-multicluster to use asmcli

---

extras/cloudsql/README.md

* The `cloudsql` extra creates a new GKE cluster on a new GCP project. See [steps here](https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/release/v0.5.4/extras/cloudsql#setup).
* In order to create a new GKE cluster, we need to first enable the [GKE API](https://cloud.google.com/kubernetes-engine/docs/reference/rest) in that new GCP project.
* Otherwise, you will get this error message:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Failed precondition when calling the ServiceConsumerManager: tenantmanager::185014: Consumer 516734428525 should enable service:container.googleapis.com before generating a service account.
com.google.api.tenant.error.TenantManagerException: Consumer 516734428525 should enable service:container.googleapis.com before …
```

Add 'Enable GKE API' step in `extras/cloudsql`

---

extras/cloudshell/tutorial.md

This PR cleans up the cloudshell tutorial.

Clean up cloudshell tutorial

---

extras/cloudshell/tutorial.md

The option in the context menu seems to have changed since this doc was written, and "Find command" is no longer in the menu.

Update wording to match context menu

---

.github/workflows/ci-pr.yaml

Ci fix review

---

.github/workflows/ci-main.yaml
.github/workflows/ci-pr.yaml
.github/workflows/terraform-validate-ci.yaml
.github/workflows/tf-validate-ci.yml

Terraform validate CI, same as https://github.com/GoogleCloudPlatform/microservices-demo/pull/1096

Terraform validate CI

---

renovate.json

Still seeing that minor, etc bumps in the PRs are not being automerged. 
Adding a `devDependency` match
Keep your eyes out for the behaviour if it's acting as expected!

Add package rules for devDependencies

---

extras/README.md

This PR adds a disclaimer README in the root of `extras/`.

Add extras/ root README

---

iac/tf-multienv-cicd-anthos-autopilot/README.md

fixes mistakes in the README.md
#1221

Fix typos in IAC TF README

---

iac/tf-multienv-cicd-anthos-autopilot/README.md

This PR adds a missing section (setting up DNS) to the IAC README.

Improve missing section in IAC README

---

src/frontend/templates/consent.html
src/frontend/templates/index.html
src/frontend/templates/login.html
src/frontend/templates/signup.html

This PR updates the copyright footer in the frontend for the year 2023.
Fixes #1438

Update footer copyright for 2023

---

.github/CONTRIBUTING.md

This PR clarifies the contributing docs with a more details step-by-step list of instructions to follow prior to creating a PR.

Clarify contributing readme

---

.github/cloudbuild/ci-pr.yaml
extras/cloudsql/kubernetes-manifests/frontend.yaml
extras/postgres-hpa/kubernetes-manifests/frontend.yaml
src/frontend/README.md
src/frontend/frontend.py
src/frontend/k8s/base/frontend.yaml
src/frontend/static/scripts/index.js
src/frontend/static/scripts/login.js
src/frontend/static/scripts/signup.js
src/frontend/static/styles/platform.css
src/frontend/static/styles/platform/alibaba.css
src/frontend/static/styles/platform/aws.css
src/frontend/static/styles/platform/azure.css
src/frontend/static/styles/platform/gcp.css
src/frontend/static/styles/platform/local.css
src/frontend/static/styles/platform/onprem.css
src/frontend/templates/consent.html
src/frontend/templates/index.html
src/frontend/templates/login.html
src/frontend/templates/shared/footer.html
src/frontend/templates/shared/html_head.html
src/frontend/templates/shared/navigation.html
src/frontend/templates/shared/platform_banner.html
src/frontend/templates/shared/scripts.html
src/frontend/templates/signup.html

Added additional functionality to display the platform, similar to Online Boutique
Added additional functionality to display the platform, similar to Online Boutique
Tested locally with skaffold, currently running in my development environment:
http://35.230.47.88

Add ENV_PLATFORM environment variable to frontend

---

.github/cloudbuild/ci-pr.yaml
.github/workflows/ui-tests/run_for_env.sh

This PR bumps the version of `skaffold` in the PR workflows to match the version in other workflows (`2.7.1`).

Bump skaffold to 2.7.1 in workflows

---

iac/tf-anthos-gke/acm.tf
iac/tf-anthos-gke/asm.tf
iac/tf-anthos-gke/gke.tf
iac/tf-anthos-gke/main.tf
iac/tf-anthos-gke/providers.tf
iac/tf-multienv-cicd-anthos-autopilot/apis.tf
iac/tf-multienv-cicd-anthos-autopilot/env-development.tf
iac/tf-multienv-cicd-anthos-autopilot/env-production.tf
iac/tf-multienv-cicd-anthos-autopilot/env-staging.tf
iac/tf-multienv-cicd-anthos-autopilot/network.tf

This PR updates the Google providers to v5 and relevant modules.

Update Google providers to v5

---

extras/cloudsql/populate-jobs/populate-accounts-db.yaml
extras/cloudsql/populate-jobs/populate-ledger-db.yaml
src/accounts/accounts-db/Dockerfile
src/accounts/accounts-db/k8s/components/init-db-job/init-db-job.yaml
src/ledger/ledger-db/Dockerfile
src/ledger/ledger-db/k8s/components/init-db-job/init-db-job.yaml

Updated the jobs to use the same container image as the database
Cleaned up the accounts-db Dockerfile
Cleaned up the ledger-db Dockerfile
Tested in my project

Database job and Dockerfile cleanup
