.github/workflows/smoke-tests.yml
kubernetes-manifests/accounts-db.yaml
kubernetes-manifests/ledger-db.yaml

Updated the databases to use statefulsets. There should be no functional change, but this is a more realistic practice. And this way makes it easier to attach persistent disks if we wanted to demo that at some point

Stateful sets

---

.github/workflows/smoke-tests.yml
.pylintrc
Makefile

Fixes #136
I have made the following changes as requested
- Created `.pylintrc` with all the disable warning IDs and their description
- Updated `smoke-tests.yml` with `--rcfile` flag
- Updated `Makefile` with `--rcfile` flag
Kindly confirm if these look okay.

Moved pylint disable flags to .pylintrc

---

src/contacts/contacts.py
src/contacts/tests/test_contacts.py
src/userservice/tests/test_userservice.py
src/userservice/userservice.py

fixes https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/196
We recently refactored Java to return plaintext error messages, instead of wrapping them in a JSON dictionary. Python was still wrapping in JSON, resulting in unfriendly error messages that could be propagated to the user: 
This PR makes Python services also return plain text on errors

Plain text Python errors

---

.github/workflows/ui-tests/cypress/integration/deposit_spec.js
.github/workflows/ui-tests/cypress/integration/transfer_spec.js

We had a flaky UI test. Sometimes it would be looking for a value $0.01 off from the true value. This likely comes down to float math issues.
This PR aims to keep stuff simple by just comparing dollar values

Fix Deposit UI Test

---

src/frontend/flask_server.py
src/loadgenerator/locustfile.py

This PR fixes #267, this uses a random generation of 15 character alphanumeric string in order to satisfy username constraints specified by #172. 
The downside of replacing the uuid creation is that we now have a probability of collisions, but since we have 62 total alphanumeric characters and a 15 character string, theres a 1/62^15 chance of collision and the number of usernames the `loadgenerator` would need to create to even get a 1% probability of collisions is > 0.01* 62^15 = 7.68*10^24. Also increased backend timeout since the userservice would finish the user creation but the frontend timeout would end just after.
Before:
After:

Fixes loadgenerator not finishing signup

---

.github/workflows/cleanup.yaml

Fixes the issue where due to the closing of PR and deletion of branch the cleanup workflow breaks due the `GITHUB_REF` environment variable referring to the default master branch after deletion of branch. Tested by closing this PR and deleted branch associated with this PR. Based on: https://stackoverflow.com/questions/62779643/how-to-extract-branch-name-on-delete-event-github-actions

Fix cleanup workflow

---

.github/workflows/ci-master.yaml

--clear flag was placed in the code coverage section, not the python unit tests.

Fix venv --clear flag placement in ci-master.yaml

---

.github/workflows/ci-master.yaml
.github/workflows/ui-tests/README.md

Fixes #93  .
- Cypress tests in ci-master were generating screenshots but running as root user.  This resulted in read-only files (Permission 0644) that could not be cleaned up by Github Actions and required manual deletion
- Updated Cypress tests to be same as ci-pr
- Updated docs with changes

Add screenshots to ci-master, update documentation

---

docs/environments.md
src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/BalanceReaderApplication.java
src/ledgerwriter/src/main/java/anthos/samples/bankofanthos/ledgerwriter/LedgerWriterApplication.java
src/transactionhistory/src/main/java/anthos/samples/bankofanthos/transactionhistory/TransactionHistoryApplication.java

Fixes #376 .
- Ensures that `projectId` is never set to null (instead, use the empty string) to prevent a Java startup crash that happens in non GCP (eg. AWS EKS) environments. The crash happens because when the pod runs outside of GKE/GCE, there is no GCE instance metadata, so calling the MetadataConfig.projectID function returns `null`. This causes Micrometer (metrics export) startup to fail. 
- Currently we have no mechanism or docs around enabling Google Cloud Trace/Monitoring export when the app itself is running in AWS. I filed an issue for this, I think we might just need Google App Default credentials mounted in as a secret. But the MetadataConfig still won't work outside of GCP. So the `projectID` won't be included in the trace …

Fix null ProjectID error when running outside of GCP

---

src/accounts-db/Dockerfile
src/ledger-db/Dockerfile

- Update `accounts-db` and `ledger-db` container base images from `postgres:12` to `postgres:12-alpine`.
- `accounts-db`: from 109.05 MB to 59.15 MB
- `ledger-db`: from 109.05 MB to 59.14 MB
No issues with the current version but that's a way to get smaller as well as more secure (less surface) images for the databases. FYI: that's also what was done with the `redis` container on that repo: https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/redis.yaml#L30.

postgres:12-alpine

---

src/ledgermonolith/README.md

Fixes #395  .
- Update ledgermonolith README to `export` environment variables

Update ledgermonolith README to export env vars for make commands

---

src/ledgermonolith/scripts/deploy-monolith.sh

Fixes #347 .
- Update GCE image for ledgermonolith to use `debian-10` instead of `debian-10-drawfork`

Fix Monolith GCE image to use public debian image

---

Makefile
README.md
src/ledgermonolith/scripts/deploy-monolith.sh

Fixes #397  .
- Update bank-of-anthos cluster creation to add the `bank-of-anthos` network tag
- Update ledgermonolith to create a firewall rule allowing connections from `bank-of-anthos`

Update ledgermonolith to properly allow bank connections via firewall

---

.github/workflows/ci-master.yaml
.github/workflows/ci-pr.yaml

Fix CI error caused by a new GH Actions change that requires a new env variable in order for `set-env` to be executed. 
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

ACTIONS_ALLOW_UNSECURE_COMMANDS: true

---

Makefile
src/ledgermonolith/README.md
src/ledgermonolith/scripts/build-artifacts.sh
src/ledgermonolith/scripts/deploy-monolith.sh

- Adds explicit set of commands to deploy the ledgermonolith with the complete Bank of Anthos application
- Updates `make cluster` to only make the k8 cluster and not deploy the app images
Folks may be using `make cluster` as a one-click deployment option for the app.  That will no longer work here.

Update ledgermonolith README with commands to run the full BoA app

---

src/ledgermonolith/init/install-script.sh
src/ledgermonolith/init/startup-script.sh
src/ledgermonolith/scripts/deploy-monolith.sh

Currently, the creation of ledgermonolith-service VM is
tailored for faster demo, by using startup-script.sh which
covers both installation activities and service startup.
This approach, however, has two main drawbacks as the script:
installs / updates binaries on every VM start
initializes / generates DB on every VM start
New version of the script:
Checks if service has been already installed
If not:
- installs pre-requisites
- downloads binaries
- initializes DB
- installs enables systemd service to run ledgermonolith app
Thanks!

Ledgermonolith install script

---

.github/workflows/README.md
.github/workflows/ci-pr.yaml

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target
Using pull request target allows PRs originating from forks to run in this repo's context, which allows those PRs to use this repo's Github secrets. Secrets are needed for the deploy tests (to access the staging cluster running in GCP).

Github actions - Add pull_request_target to CI PR to allow fork PRs

---

.github/workflows/ci-pr.yaml

Now that CI-PR uses `pull_requests_target`, the `GITHUB_SHA` no longer refers to the PR number but rather the last commit on the base branch, meaning `master`. This is causing a bug where all the PRs are being staged in `prmaster`, instead of `pr#`, resulting in clobbering. 
Get the PR # directly instead.

Fix PR_NUMBER var, use github event

---

.gitignore
.vscode/settings.json
src/frontend/frontend.py
src/frontend/templates/index.html
src/frontend/templates/login.html
src/frontend/templates/signup.html

Fixes #377 
Adds a frontend endpoint + UI info for cluster name, pod name, and node zone.

Add frontend whereami endpoint + UI info

---

dev-kubernetes-manifests/frontend.yaml
kubernetes-manifests/frontend.yaml

Improvement for #447 
**Change summary:**
- Add liveness probe to the frontend container, such that any non-responsiveness in the API for more than 30 seconds should result in the container getting restarted.
**Remaining issues / concerns:**
- There still exist an underlying issues (potentially with `gunicorn`) surrounding the frontend API not being responsive that should be addressed (thus, let's leave #447 opened.)
- Open question: The timeouts I have chosen for the liveness probe are fairly arbitrary in choosing (though intentionally longer than the readiness probe, since we don't want any unnecessary reboots if for example there was just a higher load than usual on the frontend and that the API is just taking a couple seconds to reply)
- Thought: The liveness probe does the same check …

Add liveness probe to the frontend container

---

release/README.md
release/make-release.sh

This PR extends the releasing README to add sections on creating the releasing PR, adding release notes, as well as deploying the newly released version onto the production cluster.
Additionally, I have added a check for `gcloud` being present in PATH. If it isn't, the script will go much farther than it should before failing, requiring manual processes to be performed to revert some changes (and then try again.) This early check mitigates that issue if the PATH isn't configured properly.
Testing with `gcloud` not in PATH:
```
~ ./make-release.sh
+ REPO_PREFIX=gcr.io/bank-of-anthos
+++ realpath -s ./make-release.sh
++ dirname /Users/obourgeois/workspace/repos/bank-of-anthos/release/make-release.sh
+ SCRIPT_DIR=/Users/obourgeois/workspace/repos/bank-of-anthos/release
+ …
```

Improve the releasing README with info on adding release notes and deploying on production

---

.github/workflows/ci-master.yaml
.github/workflows/ci-pr.yaml
.github/workflows/cleanup.yaml
.github/workflows/push-deploy.yml

Fixes # 
Issues with creating a new host for use by GitHub Actions pipeline. Without this change when a new host is being added to the GitHub Actions pipeline - _before it is fully setup and ready to take on jobs_ - incoming events may trigger a workflow on that un-ready host. 
To evade this, it is necessary to ensure incoming events are always scheduled on existing hosts and the new one must be used only when it is fully ready.
**_Change summary:_**
- Add a **live** label to all the Github actions workflows
- Also add the same label to the existing hosts under `Settings -> Actions`

Add gh actions label

---

release/README.md

Fixes # Missed deploy information in the release docs
- Add details about setting up service account specific to Workload Identity when deploying to Workload Identity enabled clusters

Update release docs to include info on WI prod cluster

---

README.md

- [issue]: images & links with absolute paths break when BoA is nested in another repo, i.e. [Custom Samples](https://github.com/GoogleCloudPlatform/cloud-code-custom-samples-example)
- [fix]: changed paths in main README to relative paths

Change imgs & links to relative paths in README.md

---

docs/development.md

~Fixes~ Addresses #503.
- The version of JDK and maven specified in the `docs/development.md` file is now **bolded**.
- The URLs to the JDK and maven installations lead to the specific version (not the general "Download" page). Let me know if this is a bad idea.
- I've added a note, "newer versions might cause issues", for both JDK and maven.
- This obviously doesn't "fix" #503. Ideally, Bank of Anthos would be compatible with the latest stable versions of JDK and maven.

Clarify Java & mvn requirements

---

skaffold.yaml

This PR is a rework of #490 incorporating some of the review feedback.
Update this project's use of `skaffold` to incorporate two new features:
- [multiple configuration support](https://skaffold.dev/docs/design/config/#multiple-configuration-support) that allows defining more than one `build-sync-deploy` pipeline in the same `skaffold.yaml` document.
- [configuration dependencies](https://skaffold.dev/docs/design/config/#configuration-dependencies) that allows defining dependencies between different skaffold configurations.
These two features together allow hierarchical build and deploy operations for multi-microservice and multi-repository applications. It also allows running individual _modules_ instead of the previous all-or-nothing approach.
Two examples of this being used are forks …

Split single skaffold config into modularized skaffold configs

---

docs/development.md

**Background**
* In https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/514, we update(d) the `skaffold.yaml` file that configures the development on Bank of Anthos.
* The new configuration requires `skaffold` version 1.27 or higher according to [my testing](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/514#pullrequestreview-713779181).
**Change summary:**
- Recommend `skaffold` version 1.27 or higher in the `development.md`.
**Remaining issues / concerns:**
- N/A

Recommend skaffold version in development.md

---

src/balancereader/src/main/resources/log4j2.xml
src/contacts/logging.conf
src/frontend/logging.conf
src/ledgerwriter/src/main/resources/log4j2.xml
src/transactionhistory/src/main/resources/log4j2.xml
src/userservice/logging.conf

Fixes #498
This PR makes sure that logs are displayed with the intended severity level in Cloud Operations (i.e. avoiding false classification of logs like showing all logs as error or all logs as info regardless of severity).
There are multiple ways to direct logs to Cloud Operations. For example, there are Google APIs and libraries that can be used specifically for this purpose. Alternatively, Operations is also able to read logs from known streams such as `stdout` and `stderr`. If read from those streams, it will classify all logs as `INFO` or all logs as `ERROR`, respectably. To avoid this, we can use structured logging (typically in JSON format) with specific keywords for fields that Operations recognizes.
These fields are documented here: …

Structure logs to display correctly in Cloud Operations

---

src/ledgermonolith/init/install-script.sh

Fixes #524 
- Update the `ledgermonolith` systemd service to be of type `simple` instead of `oneshot`
Tested and the VM still loads correctly (see transactions showing up):

Update ledgermonolith service to simple

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/other.md
.github/pull_request_template.md

Fixes # . N/A
- 
Adding Issue and PR templates similar to the microservice-demo (PR [here](https://github.com/GoogleCloudPlatform/microservices-demo/pull/627)) to improve context and consistency for new issues and pull requests.  Exact same files as in the microservice-demo repo.
N/A!

Added PR and issue templates

---

src/frontend/templates/index.html
src/frontend/templates/login.html

- Update CSS to change the color of the warning circle
- Minor css change
- NA
- You can either host your own cluster or check in the CI cluster
- Create port forward to the frontend: `kubectl port-forward <POD_ID> -n <NAMESPACE> 8080:8080`
- Access the Pod via `localhost:8080`
- View the error label color in the following places
- Adding a new credit card
- Login fail attempt
- Create new user with mismatching password  
- NA

cleanup: fix the background on the warning label

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

This PR bumps log4j to 2.16.0, to mitigate `CVE-2021-45046`.

Update log4j to 2.16.0

---

src/ledgermonolith/README.md
src/ledgermonolith/scripts/deploy-monolith.sh

This RP moves the canonical `ledgermonolith` artifacts to the new GCP project and GS bucket, `bank-of-anthos-ci`.
```
~ make monolith-deploy                                                                                                   
src/ledgermonolith/scripts/deploy-monolith.sh
PROJECT_ID: <redacted>
ZONE: us-east1-b
GCS_BUCKET: bank-of-anthos-ci
Cleaning up VM if it already exists...
Creating GCE instance...
Created [https://www.googleapis.com/compute/v1/projects/<redacted>/zones/us-east1-b/instances/ledgermonolith-service].
NAME: ledgermonolith-service
ZONE: us-east1-b
MACHINE_TYPE: n1-standard-1
PREEMPTIBLE:
INTERNAL_IP: <redacted>
EXTERNAL_IP: <redacted>
STATUS: RUNNING
```

Move canonical ledgermonolith artifact to bank-of-anthos-ci

---

docs/troubleshooting.md
skaffold.yaml

I noticed that images from the latest commit were pushed to `gcr.io/bank-of-anthos-ci/gcr.io/bank-of-anthos/`. This PR fixes this to push directly to `gcr.io/bank-of-anthos-ci/`.

Change the Skaffold target images to use bank-of-anthos-ci

---

dev-kubernetes-manifests/accounts-db.yaml
dev-kubernetes-manifests/balance-reader.yaml
dev-kubernetes-manifests/contacts.yaml
dev-kubernetes-manifests/frontend.yaml
dev-kubernetes-manifests/ledger-db.yaml
dev-kubernetes-manifests/ledger-writer.yaml
dev-kubernetes-manifests/loadgenerator.yaml
dev-kubernetes-manifests/transaction-history.yaml
dev-kubernetes-manifests/userservice.yaml
docs/troubleshooting.md
extras/cloudsql/kubernetes-manifests/balance-reader.yaml
extras/cloudsql/kubernetes-manifests/contacts.yaml
extras/cloudsql/kubernetes-manifests/frontend.yaml
extras/cloudsql/kubernetes-manifests/ledger-writer.yaml
extras/cloudsql/kubernetes-manifests/loadgenerator.yaml
extras/cloudsql/kubernetes-manifests/transaction-history.yaml
extras/cloudsql/kubernetes-manifests/userservice.yaml
kubernetes-manifests/accounts-db.yaml
kubernetes-manifests/balance-reader.yaml
kubernetes-manifests/contacts.yaml
kubernetes-manifests/frontend.yaml
kubernetes-manifests/ledger-db.yaml
kubernetes-manifests/ledger-writer.yaml
kubernetes-manifests/loadgenerator.yaml
kubernetes-manifests/transaction-history.yaml
kubernetes-manifests/userservice.yaml

This PR changes the K8s image refs to use the new `bank-of-anthos-ci` project.
The images were copied over using:
```
#!/bin/bash
for service in accounts-db balancereader contacts frontend ledger-db ledgerwriter loadgenerator transactionhistory userservice
do
for version in v0.1.0 v0.1.1 v0.1.2 v0.2.0 v0.3.0 v0.3.1 v0.4.0 v0.4.1 v0.4.2 v0.4.3 v0.5.0 v0.5.1
do
docker pull gcr.io/bank-of-anthos/$service:$version
docker tag gcr.io/bank-of-anthos/$service:$version gcr.io/bank-of-anthos-ci/$service:$version
docker push gcr.io/bank-of-anthos-ci/$service:$version
done
done
```
I've tested by deploying the latest release to a new cluster:
```
kubectl apply -f ./kubernetes-manifests
```
And looked at the services to see that it was using one of the newly migrated images / tags (in this case …

Change image refs to use bank-of-anthos-ci

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

This PR bumps log4j to `2.17.0` to mitigate [CVE-2021-45105](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105).

Update log4j to 2.17.0

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

This PR bumps `log4j` to `2.17.1` to mitigate [CVE-2021-44832](https://logging.apache.org/log4j/2.x/).

Bump log4j to 2.17.1

---

docs/development.md

This PR specifies the JDK requirement to be OpenJDK (rather than Oracle JDK) due to more permissive licensing.

Specify JDK requirement to OpenJDK

---

.github/workflows/cleanup.yaml

This PR removes the checkout step from the cleanup workflows. None of the cleanup steps require checking in, and attempting to do so yields errors if the branch was deleted before the cleanup job started running (race condition): https://github.com/GoogleCloudPlatform/bank-of-anthos/actions/workflows/cleanup.yaml
I will test this by deleting the branch immediately following merging.

Delete checkout step from cleanup workflows

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

Since the main branch is currently failing, this PR reverts:
- https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/ea8822461f4533dfb2df0505847c8110bad5d971
- https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/3f628543f727b61ea3f021fca6ac0e3feebf8388
- https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/4f69351bd0e4734c5a2febfd8c2976ccbdf55e1f
- https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/60d9955b7222ff41cd13fb677ba79c48e6ed8c9f
I tried to revert one at a time for each of them but they were all broken in different ways; likely they need some source code changes. I'll differ them to a later dependency bump unless we get a security notice targeting those dependencies in particular.

Revert recent Renovate Java deps bumps

---

renovate.json

Seeing that renovate-bot was using python10 for pip-compile
Added constraint to python3.7 in renovate.json (see the [docs](https://docs.renovatebot.com/modules/manager/pip-compile/))
n/a
Ensure that renovate-bot isn't using the latest python when preparing PRs
https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/650

Added python constraint to renovate.json

---

renovate.json

This PR disables `pip-requirements` for Renovate, which clashed with the `pip-compile` plugin. More details here: https://github.com/GoogleCloudPlatform/microservices-demo/pull/764

Disable pip_requirements for renovate

---

renovate.json

This PR reverts #669 since PRs are getting created without any changes to the `.txt` file, e.g.: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/675/files

Revert "Disable pip-requirements for renovate (#669)"

---

renovate.json

I saw in the DEBUG logs that renovate bot was not able to pull docker images for 3.7. Per the maintainers discussion [here](https://github.com/renovatebot/renovate/discussions/14588#discussioncomment-2326254), he suggested contraining to 3.7.0
renovate.json python constraint now says `3.7.0`
n/a
I'll keep an eye on the next debug logs when the PRs get rerun

Added pep440 contraint to renovate bot

---

renovate.json

Applying some of the results of the team's survey. This is an example PR, but it adds stability days, concurrent PR limits, and adds config to bypass that if there is a security vulnerability. Also pins our python docker image to v3.7
* Sets prConcurrentLimit to 5, stabilityDays to 7
* Sets both prConcurrentLimit and stabilityDays to 0 if it is a CVE is reported
* Also constrains python to 3.7 (before, even though it said "python":"3.7", it wasn't working. Followed up with the maintainer on why that was happening, but the solution was to use "python":"~=3.7.0" instead
Note: we also have dependabot (which is built into Github) to notify us of security vulnerabilities.
na
Similar to https://github.com/GoogleCloudPlatform/microservices-demo/pull/780

Constaint python and added config for renovate bot

---

.github/workflows/push-deploy.yml

Fixes broken push deploy tests on main. 
Importing the custom java env on the runner allows us to override with the required java 17. If we don't import this env, skaffold thinks we're using a different version of JDK that's incompatible with the java 17 version listed in our pom files. 
We're importing this env in our other github workflows (`ci-pr` and `ci-main`)  - example: https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/.github/workflows/ci-main.yaml#L117 
— so it just needs to be added to `push and deploy latest`.

[Github actions] Add java 17 source profile to push deploy workflow

---

src/balancereader/pom.xml
src/contacts/requirements.in
src/contacts/requirements.txt
src/frontend/requirements.txt
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml
src/userservice/requirements.in
src/userservice/requirements.txt

This PR bumps:
- `com.google.cloud.libraries-bom==25.1.0`
- `com.google.cloud.spring-cloud-gcp-starter==3.2.0`
- `com.google.cloud.spring-cloud-gcp-starter-trace==3.2.0`
- `com.auth0.java-jwt==3.19.1`
- `com.google.cloud.tools.jib-maven-plugin==3.2.1`
- `sqlalchemy==1.4.34`
In part to mitigate: https://tanzu.vmware.com/security/cve-2022-22965

Bump Java dependencies to mitigate CVE-2022-22965

---

dev-kubernetes-manifests/balance-reader.yaml
dev-kubernetes-manifests/contacts.yaml
dev-kubernetes-manifests/frontend.yaml
dev-kubernetes-manifests/ledger-writer.yaml
dev-kubernetes-manifests/transaction-history.yaml
dev-kubernetes-manifests/userservice.yaml
kubernetes-manifests/balance-reader.yaml
kubernetes-manifests/contacts.yaml
kubernetes-manifests/frontend.yaml
kubernetes-manifests/ledger-writer.yaml
kubernetes-manifests/transaction-history.yaml
kubernetes-manifests/userservice.yaml
release/make-release.sh

Previously, the version env was substituted manually in k8s manifests. This change makes sure that we don't miss this step by automating it. Additionally, the dev manifests now has its version statically pinned to `"dev"`.

Substitute version env correctly on release

---

extras/cloudsql/README.md
extras/cloudsql/kubernetes-manifests/balance-reader.yaml
extras/cloudsql/kubernetes-manifests/contacts.yaml
extras/cloudsql/kubernetes-manifests/frontend.yaml
extras/cloudsql/kubernetes-manifests/ledger-writer.yaml
extras/cloudsql/kubernetes-manifests/loadgenerator.yaml
extras/cloudsql/kubernetes-manifests/transaction-history.yaml
extras/cloudsql/kubernetes-manifests/userservice.yaml
extras/cloudsql/populate-jobs/populate-accounts-db.yaml
extras/cloudsql/populate-jobs/populate-ledger-db.yaml

This PR brings the Cloud SQL flavor up-to-date with v0.5.4, as well as bumps the gce-proxy to 1.30.0
Tested by following the [README instructions](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/extras/cloudsql/README.md):
```
~ k get deployments
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
balancereader        1/1     1            1           89m
contacts             1/1     1            1           89m
frontend             1/1     1            1           89m
ledgerwriter         1/1     1            1           89m
loadgenerator        1/1     1            1           89m
transactionhistory   1/1     1            1           89m
userservice          1/1     1            1           89m
```
I could deposit funds and transfer funds, which utilizes both …

Update Cloud SQL flavor to 0.5.4 and gce-proxy to 1.30.0

---

dev-kubernetes-manifests/frontend.yaml
extras/cloudsql/kubernetes-manifests/frontend.yaml
kubernetes-manifests/frontend.yaml
src/frontend/frontend.py

The `frontend` service depends on the metadata server to pull the cluster name and zone. The metadata server is not available to all flavors of Anthos.
Add the ability to change the metadata server to easily point to a simulator or set the values manually via environment variables.
Tested locally by setting the various permutation of the values in the manifest files. Left commented values in manifest files.

Added functionality to set location values and change metadata server

---

src/frontend/templates/index.html
src/frontend/templates/login.html
src/frontend/templates/signup.html

The favicon href has right double quotes instead of standard double quotes cause it to throw an error in the browser.
Changed the quotes
Tested locally

Fixed quotes around favicon

---

src/frontend/templates/login.html

When the login page initially loads or is hard refreshed the `Login failed` alertBanner is briefly displayed
Set the alertBanner to be hidden by default.
Tested locally via skaffold

Fixed login failed alertBanner flicker on initial load and hard refresh

---

src/frontend/frontend.py

See https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/760
- Changed redirect from HTTP/302 to HTTP/303 on a successful transaction
- Added 0.25 second delay to allow the transaction to propagate to `balancereader` and `transaction-history`
- Ran pep8 formatter
Tested locally with skaffold

Fixed home page refresh on successful transaction

---

dev-kubernetes-manifests/balance-reader.yaml
dev-kubernetes-manifests/ledger-writer.yaml
dev-kubernetes-manifests/transaction-history.yaml

This PR bumps the Java services' memory requests and limits to match the Pod memory requests and limits.
Making this change to reduce the cold starts and flaky tests from CI builds, without compromising on the amount of K8s nodes required for Bank of Anthos.

Bump Java res to match Pod limits and add startupProbes

---

.github/workflows/ui-tests/cypress/integration/create_spec.js
dev-kubernetes-manifests/userservice.yaml

I've been noticing some flaky frontend tests. This is causing PRs to fail on CI tests. Even clicking through the front end on URLs takes a while.
Running tests in my own GCP project, it passed (I only ran it 2 times) 
Only noticed failing tests around the create_spec.js, specifically the User can create account suites in the PRs currently
Added timeouts to the  cypress create tests.
We should remove these waits, and do a deeper investigation why.
Hopefully the CI tests pass
n/a

Bump CPU for userservice for cypress tests 

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

This PR bumps log4j to 2.18.0, essentially combining https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/877 and https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/878, since they need to happen at the same time.

Bump log4j to 2.18.0

---

extras/cloudsql/populate-jobs/populate-accounts-db.yaml

The DEFAULT_PASSHASH was not updated in the [populate-accounts-db.yaml](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/extras/cloudsql/populate-jobs/populate-accounts-db.yaml) file when the default password was changed.
Updated the DEFAULT_PASSHASH
Tested via deployment on a GKE standard cluster

Updated the DEFAULT_PASSHASH to match the new default password

---

extras/cloudsql/README.md
extras/cloudsql/create_cloudsql_instance.sh
extras/cloudsql/kubernetes-manifests/balance-reader.yaml
extras/cloudsql/kubernetes-manifests/contacts.yaml
extras/cloudsql/kubernetes-manifests/frontend.yaml
extras/cloudsql/kubernetes-manifests/ledger-writer.yaml
extras/cloudsql/kubernetes-manifests/loadgenerator.yaml
extras/cloudsql/kubernetes-manifests/transaction-history.yaml
extras/cloudsql/kubernetes-manifests/userservice.yaml
extras/cloudsql/populate-jobs/populate-accounts-db.yaml
extras/cloudsql/populate-jobs/populate-ledger-db.yaml

While trying to deploy the Bank of Anthos application using CloudSQL I encountered several issues with the populate jobs not completing. It was determined that this was due to the populate jobs having a dependency on the config.yaml manifest
- Updated to PostgreSQL 14 to match the in-cluster database
- Moved the ConfigMaps for the populate jobs to be before the Job itself.
- Added an apply of the config.yaml file before applying the populate jobs
- Added the runAsNonRoot securityContext to populate-ledger-db.yaml.
- Updated to the Bank of Anthos 0.5.6 version
- Fixed an issue with the timestamp format for one of the populate jobs. The default date utility on Alpine does not support
%N as it is a GNU extension.
Tested in a Qwiklab environment using a GKE Standard cluster.

CloudSQL fixes

---

src/ledgermonolith/config.yaml

Fixed #908 by bringing the ledgermonolith config in-line with 0.5.6 changes (specifically, this change: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/855)

Update ledgermonolith config to be in-line with 0.5.6

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

`openjdk:17-slim` for `ledgerwriter`, `balancereader`, `transactionhistory` and `ledgermonolith`.
All the Java container images are now in `-slim` like it was already the case for the Python container images.
I also added the `<to>` section (in addition to the `<from>` one already existing) to make sure it's taking the right image, [apparently this field is mandatory](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#to-object).
The images went from the size of 318.2 MB to 296.7 MB.

`openjdk:17-slim`

---

renovate.json

With this https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/933, I just saw that Renovate was still configured for Python 3.7, but all the Python apps are now in 3.10.

update python 3.10.0 for Renovate

---

release/make-release.sh

This PR adds a missing line to the release script which I noticed while release 0.5.7 earlier today.
This line is a follow-up of https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/881

Add missing git add to release script

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

`openjdk:17-slim` --> `openjdk:17-alpine`
Before: 297.2 MB - 51 vulnerabilities
After: 268.3 MB -  16 vulnerabilities
_Note: also did a cleanup with the `<to>` sections not used at all, only `<from>` counts apparently._

`openjdk:17-slim` --> `openjdk:17-alpine`

---

src/contacts/requirements.in
src/contacts/requirements.txt
src/frontend/requirements.in
src/frontend/requirements.txt
src/userservice/requirements.in
src/userservice/requirements.txt

This PR bumps OpenTel to 1.13.0, alongside relevant instrumentation modules.

Bump opentel to 1.13.0

---

src/balancereader/pom.xml
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

OpenJDK is now deprecated (https://hub.docker.com/_/openjdk), so this PR moves the Java images to eclipse-temurin (https://hub.docker.com/_/eclipse-temurin) instead.
Fixes #879 
This idecreases size and reduces the amount of vulnerabilities.
**Size:** 268MB -> 145MB
**Vulns:** 16 -> 1

Change Java images from openjdk to eclipse-temurin's JRE

---

src/loadgenerator/locustfile.py

Handle to avoid calls of authenticated endpoints when logout has already been called
Almost 50% of authenticated requests are failing with error code 401 because of the request-logout race.
Fixed logic on how signup+login and logout works. Also made some small improvements.

Fix loadgenerator race condition

---

src/contacts/Dockerfile
src/frontend/Dockerfile
src/loadgenerator/Dockerfile
src/userservice/Dockerfile

Like we did in Online Boutique https://github.com/GoogleCloudPlatform/microservices-demo/pull/1168, let's have the Python container base images have now their version as `Ma.Mi.Re` instead of just `Ma.Mi`. As a best practice, this will allow to catch and track CVE vulnerabilities as early as possible.
In this specific case, fixing this: `CVE-2022-40674 | Critical | 9.8 | Yes | expat | OS`.

`python:3.10.8-slim`

---

src/accounts-db/Dockerfile
src/balancereader/pom.xml
src/ledger-db/Dockerfile
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

Doesn't change anything yet with the current version because `eclipse-temurin:17-jre-alpine` and `eclipse-temurin:17.0.4.1_1-jre-alpine` are the same as of now (same for `postgres:15-alpine` and `postgres:15.0-alpine`). But it's following up on https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1041 and https://github.com/GoogleCloudPlatform/microservices-demo/pull/1204 in order to better track/catch CVEs vulns fix in the future.

`eclipse-temurin:17.0.4.1_1-jre-alpine` + `postgres:15.0-alpine`

---

dev-kubernetes-manifests/frontend.yaml

For consistency, fixing the container name from `front` to `frontend`.
I don't see any breaking change with that. I found this issue when doing Kustomize with the Kubernetes manifests, when patching based on the container name, by consistency, I was taking the name of the service as the container name but found out the hard way that the container name of the `frontend` deployment was `front`.
So proposing this fix. Otherwise in my Kustomize I could just patch the `front` container name, but thought it would be ideal to have this fix for consistency (and maybe avoiding any friction for someone who will try this). Let me know what do you think.

Fix typo in `frontend` container name

---

src/contacts/requirements.txt
src/loadgenerator/requirements.txt
src/userservice/requirements.txt

This PR bumps greenlet to 2.0.0.
Fixes https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1058 and https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1062

Bump greenlet to 2.0.0

---

docs/development.md
skaffold.yaml

This PR bumps Skaffold to 2.0 (a major bump). To update the manifest to `skaffold/v3`, `skaffold fix` was utilized.

Bump skaffold to 2.0 and manifest to v3

---

src/userservice/tests/test_userservice.py

This PR makes sure that the unit test for the userservice are using the same JWT token expiry than prod, which is currently set to 3,600 (https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/dev-kubernetes-manifests/userservice.yaml#L62-L63)
This fix is an attempt to fix a flaky test that sometime fails with `jwt.exceptions.ExpiredSignatureError: Signature has expired`, which was seen both on the main branch, and in PRs, e.g.:
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1071
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1080

Bring unit test JWT token expiry in-line with prod

---

src/balancereader/pom.xml
src/ledgerwriter/pom.xml
src/transactionhistory/pom.xml

This PR bumps micrometer to `1.10.0` _and_ adds a BOM pinning it to fix https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1078 where Spring was depending on an older version of micrometer.

Bump micrometer to 1.10.0

---

src/ledgermonolith/init/install-script.sh

This PR adds Java 17 in the ledgermonolith VM. In the background, I have also just pushed a new version of the ledgermonolith to GCS.
Fixes #1096
I have just finished testing this:

Add Java 17 to ledgermonolith VM

---

.github/workflows/cleanup.yaml

This fixes an occasional issue where the cleanup workflow is attempting to clean-up a namespace that was already cleaned up previously (i.e. it's "not found"), making sure that the workflow doesn't result in a failure if that's the case.
This was seen in a few PRs, more recently: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1111

Fix cleanup workflow when namespace is not found

---

renovate.json
src/accounts-db/Dockerfile
src/balancereader/pom.xml
src/contacts/Dockerfile
src/frontend/Dockerfile
src/ledger-db/Dockerfile
src/ledgermonolith/pom.xml
src/ledgerwriter/pom.xml
src/loadgenerator/Dockerfile
src/transactionhistory/pom.xml
src/userservice/Dockerfile

Use `digest` instead of `tag` for container base images.
This follows best practices: https://cloud.google.com/architecture/using-container-images.
> We recommend that you pin your Docker images to an exact digest. By pinning to a digest you make your Docker builds immutable, every time you do a pull you get the same content.
And this will allow to catch as early as possible container base images updates when we target images such as: `python:3.11.0-slim`, etc. which are mutable. See illustration there too: https://github.com/GoogleCloudPlatform/microservices-demo/pull/1293#issuecomment-1324140441
Renovate will still update the base images for us: https://docs.renovatebot.com/docker/#digest-updating

Use `digest` instead of `tag` for container base images

---

src/contacts/Dockerfile
src/frontend/Dockerfile
src/loadgenerator/Dockerfile
src/userservice/Dockerfile

Multi-stage build in Python `Dockerfiles` to decrease container image size (and potentially the surface of attack), like we do there https://github.com/GoogleCloudPlatform/microservices-demo.
- `loadgenerator`: 85.9MB --> 63.1MB (-22.8MB)
- `contacts`: 104.4MB --> 76MB (-28.4MB)
- `frontend`: 79.9MB --> 61.7MB (-18.2MB)
- `userservice`: 104.4MB --> 76MB (-28.4MB)
Note: no change on the number of CVEs.

Multi-stage build in Python `Dockerfiles` to decrease container image size

---

renovate.json

Update renovate.json to look at container images to update in Kubernetes manifests.
It will help for example keeping up to date the container images in these Kubernetes manifests: https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/main/extras/cloudsql/kubernetes-manifests (`gce-proxy`, etc.).
https://docs.renovatebot.com/modules/manager/kubernetes/
As soon as it's merged in `main`, the goal is to catch any update of any container images referenced in any Kubernetes manifests.

Update renovate.json to look at container images to update in Kubernetes manifests

---

renovate.json

Renovate bot has been noisy. Adding package rules (similar to [online boutique](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1412#issuecomment-1353764698) in auto-merging if tests pass for any dependencies less than minor. 
Adding `packageRules` ([docs](https://docs.renovatebot.com/configuration-options/#packagerules)). 
n/a
Keep an eye our for anything less than a minor bump PR, seeing if it behaves properly!

Adding automerge in renovate config

---

renovate.json

We were not seeing the expected automerge behavior
Added the platform automerge field in the `renovate.json`. [ Doc here](https://docs.renovatebot.com/configuration-options/#platformautomerge)
```
platformAutomerge will configure PRs to be merged after all (if any) branch policies have been me
```
none!
n/a
https://github.com/GoogleCloudPlatform/microservices-demo/pull/1420

Add platformAutomerge

---

renovate.json

This PR increases the number of concurrent PRs that Renovate can have open from 5 to 10.
This allows more buffer for when there are blocked PRs (e.g. https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1040 which is waiting for a Request update) so that Renovate continues creating new PRs and they don't get queued.

Bump Renovate's concurrent limit to 10

---

src/balancereader/pom.xml
src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/BalanceReaderApplication.java
src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/BalanceReaderController.java
src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/Transaction.java
src/ledgermonolith/pom.xml
src/ledgermonolith/src/main/java/anthos/samples/bankofanthos/ledgermonolith/LedgerMonolithApplication.java
src/ledgermonolith/src/main/java/anthos/samples/bankofanthos/ledgermonolith/LedgerMonolithController.java
src/ledgermonolith/src/main/java/anthos/samples/bankofanthos/ledgermonolith/Transaction.java
src/ledgerwriter/pom.xml
src/ledgerwriter/src/main/java/anthos/samples/bankofanthos/ledgerwriter/LedgerWriterApplication.java
src/ledgerwriter/src/main/java/anthos/samples/bankofanthos/ledgerwriter/LedgerWriterController.java
src/ledgerwriter/src/main/java/anthos/samples/bankofanthos/ledgerwriter/Transaction.java
src/transactionhistory/pom.xml
src/transactionhistory/src/main/java/anthos/samples/bankofanthos/transactionhistory/Transaction.java
src/transactionhistory/src/main/java/anthos/samples/bankofanthos/transactionhistory/TransactionHistoryApplication.java
src/transactionhistory/src/main/java/anthos/samples/bankofanthos/transactionhistory/TransactionHistoryController.java

This is a PR to upgrade the project to Spring Boot 3 and Spring Cloud GCP 4.0.
- Add the Spring Cloud GCP BOM to manage our versions going forward while we’re here.
- Remove the types from our ResponseEntity instantiations.
- Replace all javax.* imports with Jakarta.* counterparts
- Exclude the ZipkinAutoConfiguration with each submodule’s @SpringBootApplication annotation

Upgrade to Spring Boot 3 and Spring Cloud GCP 4

---

extras/prometheus/README.md
extras/prometheus/gmp/README.md
extras/prometheus/gmp/alertmanager.yaml
extras/prometheus/gmp/blackbox-exporter.yaml
extras/prometheus/gmp/probes.yaml
extras/prometheus/gmp/rules.yaml
extras/prometheus/oss/README.md
extras/prometheus/oss/alertmanagerconfig.yaml
extras/prometheus/oss/probes.yaml
extras/prometheus/oss/rules.yaml
extras/prometheus/oss/values.yaml

This PR contains manifest files for the setup of the microservices liveness probes with Prometheus (OSS and GMP)
* Configure the liveness probes with help of Blackbox exporter probes
* Configure Alert rules
* Configure Alertmanager to send notifications via Slack channel

Microservices liveness probes with help of Prometheus 

---

Makefile
src/ledgermonolith/README.md
src/ledgermonolith/init/install-script.sh

The README was not up to date and did not work. You could only use the script to deploy both the service and database to the same instance. We have use cases where we would like to deploy the service and database on separate instances.
Updated the README and makefile to work properly.
Updated the install-script to allow for installing the service and database on separate instances
Tested using the updated README and [Migrating a monolith VM](https://cloud.google.com/migrate/containers/docs/migrating-monolith-vm-overview-setup)

Updated ledgermonolith README and modified init script to handle multi-instance installations

---

release/README.md

This PR adds a step near the end of the releasing README to rebuilt the ledgermonolith, if applicable.

Add ledgermonolith build step to release README

---

src/contacts/requirements.in
src/contacts/requirements.txt
src/frontend/requirements.in
src/frontend/requirements.txt
src/userservice/requirements.in
src/userservice/requirements.txt

This PR bumps opentelemetry to version `1.16`.
This takes care of https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1300 and https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1301 while also bumping all relevant modules to `0.37b0`.

Bump opentelemetry to 1.16.0

---

.github/auto-approve.yml
CODEOWNERS

This PR enabled the `auto-approve` bot.
Docs: https://github.com/googleapis/repo-automation-bots/tree/main/packages/auto-approve

Add auto-approve bot config

---

iac/tf-anthos-gke/acm.tf

Fixes problem with upgrade to v25 of ACM module
Upgrading BoA terraform to use v25 of the ACM module results in the following error when trying to deploy the application:
Error: Invalid index
│
│   on .terraform/modules/acm/modules/acm/[outputs.tf](http://outputs.tf/) line 37, in output "acm_metrics_writer_sa":
│   37:   value       = google_service_account.acm_metrics_writer_sa[0].email
│     ├────────────────
│     │ google_service_account.acm_metrics_writer_sa is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
Setting the metrics SA parameter to true in this config fixes the problem

Set metrics SA parameter

---

src/frontend/frontend.py

When logging into bank of anthos through the frontend, oftentimes the login will fail as the userservice takes a while (3-6-ish seconds) to respond and frontend has a default timeout of 4s.
Doubled the timeout on calling the /login endpoint of the userservice.
Login to bank-of-anthos through frontend
Follow-up: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1221

Fix login timeouts when using frontend

---

.github/trusted-contribution.yml

This PR adds a config for [trusted-contribution](https://github.com/googleapis/repo-automation-bots/tree/main/packages/trusted-contribution) to auto-comment `/gcbrun` on PRs created by [renovate-bot](https://github.com/renovate-bot).
This is required because Cloud Run does not run for external contributors. This is intended behaviour for untrusted contributors, but is inconvenient for trusted bot contributors such as Renovate. This PR prevents us from having to manually comment `/gcbrun` on every incoming Renovate PR.

Add trusted-contribution config

---

src/accounts/contacts/k8s/base/contacts.yaml
src/accounts/userservice/k8s/base/userservice.yaml
src/frontend/k8s/base/frontend.yaml
src/ledger/balancereader/k8s/base/balancereader.yaml
src/ledger/ledgerwriter/k8s/base/ledgerwriter.yaml
src/ledger/transactionhistory/k8s/base/transactionhistory.yaml

This PR reverts request and limit changes that were done as part of https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1221 to match what is currently in the [latest release](https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/main/kubernetes-manifests). This is due to the fact that the aforementioned increase prevents Bank of Anthos from running in default GKE Standard clusters, which will inevitably break existing tutorial, blog posts, and other content that relies on that staying true.
**Testing**
Deployed on a standard, default, 3-node GKE cluster:
```
~ k get pods
NAME                                  READY   STATUS    RESTARTS   AGE
accounts-db-0                         1/1     Running   0          5m23s
balancereader-7cf585b885-h74p9        1/1     Running   0 …
```

Revert request and limit changes

---

docs/README.md

This PR:
- Fixes links in the root README to be absolute
- Redirects the uptime shield to the production environment
- Updates the list of demos where Bank of Anthos is used
Staged:
- https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/issue-fix-readme/docs/README.md

Fixes links in root README and update list of demos

---

src/accounts/userservice/k8s/base/userservice.yaml

This PR bumps the `userservice` by 10Mi to stay within the 3-node constraints of GKE Standard but to also speed up e2e tests.
Todo: update this description with results once tests have finished running--

Bump userservice by 10Mi

---

.github/trusted-contribution.yml

This PR adds `dependabot` to the list of trusted contributors, which will auto-comment `/gcbrun` (Cloud Build) to comment this bot opens.

Add dependabot as trusted contributor

---

src/accounts/contacts/requirements.in
src/accounts/contacts/requirements.txt
src/accounts/userservice/requirements.in
src/accounts/userservice/requirements.txt
src/frontend/frontend.py
src/frontend/requirements.in
src/frontend/requirements.txt
src/loadgenerator/requirements.txt

This PR bumps flask to 2.3.2, fixing:
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1477
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1478
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1479

Bump flask to 2.3.2

---

.github/auto-approve.yml

This PR adds a few new auto-approve extensions to Bank of Anthos, which were released here: https://github.com/googleapis/repo-automation-bots/pull/5053

Add Python and Docker extensions to auto-approve

---

iac/tf-anthos-gke/acm.tf
iac/tf-anthos-gke/asm.tf

Add wait that we can use in acm.tf. This helps ensure that Bank of Anthos doesn't start up until the Istio injection label is applied so we don't need to restart to get proxies.
Before this PR, we saw inconsistent behaviour when applying Bank of Anthos - sometimes the ASM proxies were up for all services when the apply was complete, sometimes for only some services, and sometimes for no services. Users needed to restart all pods to get the desired ASM behaviour.
- Added new wait resource
- Added dependency on the wait resource in acm.tf
- Removed enabling metrics SA in acm.tf as this doesn't seem to be required any more and causes issues with adding dependencies

Add new wait resource

---

src/accounts/contacts/requirements.in
src/accounts/contacts/requirements.txt
src/accounts/userservice/requirements.in
src/accounts/userservice/requirements.txt
src/frontend/requirements.in
src/frontend/requirements.txt

This PR bumps OpenTel to `1.19.0`, and relevant modules to `0.40b`.

Bump OpenTel to 1.19.0

---

src/accounts/cloudbuild.yaml
src/frontend/cloudbuild.yaml
src/ledger/cloudbuild.yaml

This PR bumps Skaffold images used in Cloud Build for `2.6.1`.

Bump skaffold to 2.6.1

---

docs/ci-cd-pipeline.md
iac/tf-multienv-cicd-anthos-autopilot/apis.tf
iac/tf-multienv-cicd-anthos-autopilot/main.tf
iac/tf-multienv-cicd-anthos-autopilot/terraform.tfvars
iac/tf-multienv-cicd-anthos-autopilot/variables.tf

- `certificatemanager.googleapis.com` API was not enabled
-  Cloud storage bucket was not globally unique
- Added `certificatemanager.googleapis.com` API
- Created a globally unique bucket bucket name
- Cleaned up formatting
Tested on my project

Updates to CI/CD pipeline

---

src/ledgermonolith/scripts/deploy-monolith.sh

This repo is used in the Anthos labs in Qwiklabs. We are asking every lab developer to stop using N1 series machines and use only E2 series machines, which are cheaper to run and less prone to resource starvation issues.

cleanup: Use e2 series machine instead of n1 for the ledgermonolith VM

---

src/accounts/contacts/requirements.in
src/accounts/contacts/requirements.txt
src/accounts/userservice/requirements.in
src/accounts/userservice/requirements.txt
src/frontend/requirements.in
src/frontend/requirements.txt

This PR manually bumps OpenTel to 1.20, fixing:
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1773
- https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1774

Bump opentel to 1.20.0

---

src/accounts/cloudbuild.yaml
src/frontend/cloudbuild.yaml
src/ledger/cloudbuild.yaml

This PR removes the experimental Skaffold version flag from the Cloud Deploy release creation. This flag used to be necessary when it was added since we were relying on Skaffold changes that were not included in the default Cloud Deploy release, but nowadays Cloud Deploy uses Skaffold 2.6 by default which is more than sufficient for our needs.

Remove preview skaffold version from Cloud Build / Deploy step

---

src/ledger/balancereader/pom.xml
src/ledger/ledgerwriter/pom.xml
src/ledger/transactionhistory/pom.xml

* The `<resources>` element inside the `pom.xml` file tells the project (`balancereader` microservice in this case) where its [project resources](https://maven.apache.org/plugins/maven-resources-plugin/examples/resource-directory.html) are. Project resources includes the [`application.properties` file](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/release/v0.6.1/src/ledger/balancereader/src/main/resources/application.properties).
* Currently, the `pom.xml` points to `src/` while the `application.properties` file exists in the `src/main/resources` folder.
* So the `balancereader` never picks up on its [`application.properties` file](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/release/v0.6.1/src/ledger/balancereader/src/main/resources/application.properties).
* …

Update pom.xml to use src/main/resources

---

.github/renovate.json5

This new renovate config will run weekly, and group PRs based on the "language"
(actually the renovate manager).
This should reduce the number of PRs and PR conflicts significantly, down to
~5/wk instead of ~15. And eliminate issues with tightly-coupled dependencies.

feat(renovate): group PRs by language and schedule weekly

---

.github/renovate.json5

Include lockfileMaintenance updates (for package-lock.json and pip-compile'd
requirements.txt files) in the same PR as other updates
also increases rate limits, to allow more PRs to be created at once, since we're
only running once a week.

feat(renovate): include lockfile updates with other updates

---

extras/backup/README.md
extras/backup/kubernetes-manifests/accounts-db.yaml
extras/backup/kubernetes-manifests/ingress.yaml
extras/backup/kubernetes-manifests/ledger-db.yaml
extras/backup/substitution-rules.yaml
extras/backup/transformation-rules.yaml
src/accounts/accounts-db/k8s/overlays/development/kustomization.yaml
src/ledger/ledger-db/k8s/base/config.yaml
src/ledger/ledger-db/k8s/overlays/development/kustomization.yaml

This PR contains files and changes to demonstrate the usage of Backup for GKE in the scope of migration from Standard to Autopilot.
I have added additional labels to account-db and ledger-db development manifests to make them similar to other workloads. Also, these changes are needed for the tutorial. Unfortunately, I can't move this PR to `kubernetes-engine-samples` repo because the tutorial is based on BoA application.

Example of usage Backup for GKE

---

README.md
docs/ci-cd-pipeline.md
docs/releasing/README.md
extras/tls-domain-managedcerts/managed-certificates.yaml
src/frontend/k8s/overlays/production/managed-certificate.yaml

This PR changes the live demo URL from `bank-of-anthos.xyz` to `cymbal-bank.fsi.cymbal.dev`.

Change live demo domain to cymbal.dev

---

src/accounts/accounts-db/k8s/components/init-db-job/init-db-job.yaml
src/components/cloud-sql/cloud-sql-proxy/add-container.yaml
src/components/cloud-sql/cloud-sql-proxy/replace-args-job.yaml
src/components/cloud-sql/kustomization.yaml
src/components/cloud-sql/ledger-db.yaml
src/ledger/ledger-db/k8s/components/init-db-job/init-db-job.yaml

- Updated to Cloud SQL Proxy v2 in preparation for some upcoming fleet workload identity work
Tested in my project using https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/docs/ci-cd-pipeline.md
- [dev](http://34.82.215.65)
- [staging](http://34.83.32.172)
- [prod](https://boa.prod.rueth.io)

Updated to Cloud SQL Proxy v2

---

src/ledger/balancereader/src/main/resources/application.properties
src/ledger/ledgerwriter/src/main/resources/application.properties
src/ledger/transactionhistory/src/main/resources/application.properties

Log messages for DB related issues are not very helpful, an example:
```
buildNativeEntityManagerFactory | Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
refresh | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unable to create requested service …
```

Set the spring.jpa.database-platform to provide better log messages

---

src/ledger/balancereader/src/main/resources/application.properties
src/ledger/ledgerwriter/src/main/resources/application.properties
src/ledger/transactionhistory/src/main/resources/application.properties

Even with `spring.sleuth.enabled` set to `false`, zipkin2 tried to lookup the ADC credentials. This causes the application to crash on some environments. 
Added `spring.cloud.gcp.trace.enabled`  to be set via the `ENABLE_TRACING` environment variable as well to fully disable the trace functionality in the apps.
Tested on my personal machine using Docker Desktop.

Disabled spring.cloud.gcp.trace to stop ADC lookup

---

extras/prometheus/gmp/rules.yaml

Incorrect escaping of YAML when included on cloud.google.com/docs (such as https://cloud.google.com/kubernetes-engine/enterprise/docs/learn/scalable-apps-monitor#rules), and also some spelling mistakes.
Correct spelling mistakes for multiple instances of "unavailable" throughout and for "Contacts", and correct grammar / incorrect escaping for "it's".
Deploy `rules.yaml` into a cluster that has Cymbal Bank and Prometheus running (such as https://cloud.google.com/kubernetes-engine/enterprise/docs/learn/scalable-apps-monitor).

Update spelling and grammar in rules.yaml

---

iac/tf-multienv-cicd-anthos-autopilot/env-production.tf
iac/tf-multienv-cicd-anthos-autopilot/env-staging.tf

An [issue](https://github.com/terraform-google-modules/terraform-google-sql-db/issues/624) in the unpinned [postgresql](https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/postgresql) module was causing Terraform to fail to run.
- Pin to a known good version (v20)
- Trivial trailing whitespace fix

fix: Pin postgresql module to known good version

---

iac/tf-multienv-cicd-anthos-autopilot/main.tf

With recent versions of the Google Terraform providers, Config Sync was not being enabled in clusters for the `tf-multienv-cicd-anthos-autopilot` deployment, causing clusters to fail to sync.
Pin the providers to a tested and known good version, pending further investigation into the provider changes.
###
Fixes #2200.

fix: Pin Google Terraform providers to known good version

---

src/accounts/contacts/Dockerfile
src/accounts/userservice/Dockerfile
src/frontend/Dockerfile

The following services were failing to start (state of `CrashLoopBackOff`), because of missing file permissions in `/app` for non-root users:
- `contacts`
- `userservice`
- `frontend`
Update Dockerfile to modify permissions of files in `/app` so they are readable by all users.
#2193

fix: Ensure application files are readable by non-root users

---

Makefile
docs/development.md
docs/troubleshooting.md

This PR removes references to `gcr.io` in the docs.
Release images have all moved to `us-central1-docker.pkg.dev` a long time ago, and that's what the instructions should use too.
The only references left are those of older images in `extras/`, but those images remain accessible. When those extras are updated with newer images they'll use the `us-central1-docker.pkg.dev` tags.

Remove gcr.io references in the docs

---

README.md

Checks badge sees neutral checks as a negative, showing a failure badge instead of a success. Commenting out for now.

Hide checks badge from the README temporarily
